---
- name: Fish config directories
  file: path={{ ansible_user_dir }}/.config/fish/functions
        state=directory

- name: Clone Fisherman
  git: dest={{ ansible_user_dir }}/src/fisherman
       repo=https://github.com/fisherman/fisherman.git
       depth=1
       force=true
       update=yes
  register: fisherman_status

- name: Install Fisherman
  command: make
           chdir={{ ansible_user_dir }}/src/fisherman
  when: fisherman_status.changed
  register: fisherman_install_status

- name: Install Fisherman Plugins
  shell: fisher install {{ item }} \nend
  args:
    executable: /usr/local/bin/fish
    creates: ~/.config/fisherman/cache/{{item}}
  with_items:
    - bass
    - bobthefish
    - fasd
    - fzf
    - grc
    - thefuck
  when: fisherman_install_status.changed

- name: Fish Config
  file: src={{ ansible_env.PWD }}/files/config/fish/config.fish
        dest={{ ansible_user_dir }}/.config/fish/config.fish
        state=link
        force=yes

- name: Fish user key bindings
  file: src={{ ansible_env.PWD }}/files/config/fish/functions/fish_user_key_bindings.fish
        dest={{ ansible_user_dir }}/.config/fish/functions/fish_user_key_bindings.fish
        state=link
        force=yes
