---
- name: Symlink dotfiles
  file: src={{ ansible_env.PWD }}/files/{{ item }}
        dest={{ ansible_user_dir }}/{{ item }}
        state=link
        force=yes
  with_items:
    - .gitignore
    - .gitconfig
    - .git-commit-template.txt
    - .tmux.conf
    - .vimrc
    - .asdfrc

- import_tasks: emacs.yml
- import_tasks: fish.yml
- import_tasks: asdf.yml
- import_tasks: tmux.yml
- import_tasks: vim.yml
