---
- name: Vim autoload directory present
  file: path={{ ansible_user_dir }}/.vim/autoload
        state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ ansible_user_dir }}/.vim/autoload/plug.vim"
