---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Install Homebrew formula
  homebrew:
    name:
      - git
      - wget
      - curl
      - coreutils
      - emacs
      - fish
      - legit
      - jq
      - reattach-to-user-namespace
      - the_silver_searcher
      - tmux
      - watchman
      - thefuck
      - grc
      - fasd
      - fzf
    state: latest

- name: Symlink coreutils
  file: src=/usr/local/bin/{{ item.src }}
        dest=/usr/local/bin/{{ item.dest }}
        state=link
        force=yes
  with_items:
    - src: gtac
      dest: tac

- name: Cleanup Homebrew
  command: brew cleanup
